#!/bin/sh
# Toggle on/off an thirdal monitor, HDMI does not support audio over HDMI as it's pretending that it's DVI

# copied. Make sure to check!

# main="$1"
# second="$2"
# third="$3"
intern="eDP-1"
# extern="HDMI-1"
# work="DP-2"
# extern="DP-4"


# extern=$(xrandr | grep -P "^\w+-[0-9]+ connected" | grep -vP "eDP-1" | sed -e 's/ .*$//' | dmenu)
extramonitor() {
	# extern=$(xrandr | grep -P "^\w+-[0-9]+ connected" | grep -vP "(Screen)|(eDP-1)" | sed -e 's/ .*$//' | dmenu)
	extern=$(xrandr | grep -P "^\w+-[0-9]+" | grep -vP "(Screen)|(eDP-1)" | sed -e 's/ .*$//' | dmenu)
  case "$1" in
      "disconnect") xrandr --output "$extern" --off --output "$intern" --auto ;;
      # "extra") xrandr --output "$extern" --mode 2560x1440 --auto --right-of "$intern" ;;
      "duplicate") xrandr --output "$intern" --auto --output "$extern" --auto --same-as "$intern" ;;
      # "connect") xrandr --output "$extern" --mode 2560x1440 && xrandr --output "$intern" --auto --output "$extern" --right-of "$intern" ;;
      "connect") xrandr --output "$extern" --auto && xrandr --output "$intern" --auto --output "$extern" --right-of "$intern" ;;
      "connectWork") xrandr --output "$work" --auto --scale 1.5x1.5 --right-of "$intern" ;;
      "disconnectWork") xrandr --output "$work" --off --output "$intern" --auto ;;
      # "main+4kthird") xrandr --output "$third" --mode 3840x2160 && xrandr --output "$main" --auto --output "$third" --right-of "$main" ;;
      # "main+second") xrandr --output "$second" --mode 1920x1080 && xrandr --output "$main" --auto --output "$second" --left-of "$main" ;;
      # "main+third") xrandr --output "$third" --mode 1920x1080 && xrandr --output "$main" --auto --output "$third" --right-of "$main" ;;
      # "allthree") xrandr --output "$second" --mode 1920x1080 && xrandr --output "$third" --mode 1920x1080 && xrandr --output "$main" --auto --output "$second" --left-of "$main" --output "$third" --right-of "$main";;
      # "duplicate") xrandr --output "$" --set audio force-dvi --mode 1920x1080 && xrandr --output "$main" --auto --output "$third" --same-as "$main" ;;
      # *) notify-send "Multi Monitor" "Unknown Operation" ;;
  esac
}

# selection=$(printf "allthree\nmain+4kthird\nmain+third\nmain+second\ndisconnect\nduplicate" | dmenu -i -p "Monitor Configuration")
# extramonitor "$selection" && fixdualhead -pd "1 2 3 4 5 6 7" -p "$main" -s "$second" -sd "8 9 0"
